# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlSrAU8wETk8Q9NqVIUyg4wGtAsnKYHS
"""

import random
import itertools

cities = ['A','B','C','D','E']
distances = {
    ('A','B'): 2, ('A','C'): 9, ('A','D'): 10, ('A','E'): 7,
    ('B','C'): 6, ('B','D'): 4, ('B','E'): 3,
    ('C','D'): 8, ('C','E'): 5,
    ('D','E'): 1
}


def path_distance(path):
    dist = 0
    for i in range(len(path)-1):
        pair = (path[i], path[i+1])
        if pair not in distances:
            pair = (path[i+1], path[i])
        dist += distances[pair]

    dist += distances.get((path[-1], path[0]), distances.get((path[0], path[-1]),0))
    return dist


min_dist = float('inf')
best_path = None

for perm in itertools.permutations(cities):
    d = path_distance(perm)
    if d < min_dist:
        min_dist = d
        best_path = perm

print("Best Way (Problem Solving):", best_path)
print(" Best Distance:", min_dist)


def fitness(path):
    return -path_distance(path)


def create_individual():
    path = cities[:]
    random.shuffle(path)
    return path

def crossover(p1, p2):
    cut = random.randint(1,len(cities)-2)
    child = p1[:cut] + [c for c in p2 if c not in p1[:cut]]
    return child

def mutate(path):
    i,j = random.sample(range(len(cities)),2)
    path[i], path[j] = path[j], path[i]


population = [create_individual() for _ in range(20)]

for gen in range(100):
    population = sorted(population, key=lambda x: fitness(x), reverse=True)
    new_pop = population[:5]
    while len(new_pop) < 20:
        p1,p2 = random.sample(population[:10],2)
        child = crossover(p1,p2)
        if random.random() < 0.2:
            mutate(child)
        new_pop.append(child)
    population = new_pop

best = population[0]
print("Best Way(Genetic Algorithm):", best)
print("Best Distance(GA):", -fitness(best))