# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gDnt7KSd0CPdk7pulqfFa2t3I-Ni5hx
"""

from collections import deque

cities = ['A','B','C','D','E']
distances = {
    ('A','B'): 2, ('A','C'): 9, ('A','D'): 10, ('A','E'): 7,
    ('B','C'): 6, ('B','D'): 4, ('B','E'): 3,
    ('C','D'): 8, ('C','E'): 5,
    ('D','E'): 1
}

def get_distance(a,b):
    return distances.get((a,b), distances.get((b,a),0))

queue = deque()
queue.append(('A',['A'],0))

min_cost = float('inf')
best_path = None

while queue:
    current, path, cost = queue.popleft()

    if len(path) == len(cities):
        cost += get_distance(current, path[0])
        if cost < min_cost:
            min_cost = cost
            best_path = path + [path[0]]
        continue

    for city in cities:
        if city not in path:
            queue.append((city, path + [city], cost + get_distance(current, city)))

print("The Best Way:", best_path)
print("The shortest Distance", min_cost)